

cc_binary(
    name = "pingpong_bench",
    srcs = "bench.cc",
    deps = "//muduo/net:muduo_net",
    optimize = ["-std=c++11", "-g", "-O2", "-Wall", "-Wextra",],
)

cc_binary(
    name = "pingpong_server",
    srcs = "server.cc",
    deps = "//muduo/net:muduo_net",
    optimize = ["-std=c++11", "-g", "-O2", "-Wall", "-Wextra",],
)

cc_binary(
    name = "pingpong_client",
    srcs = "client.cc",
    deps = "//muduo/net:muduo_net",
    optimize = ["-std=c++11", "-g", "-O2", "-Wall", "-Wextra",],
)

